name: Maven Build

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Maven Central
        uses: rosestack/maven-build-action@main
        with:
          working-directory: 'test-project'
